language: node_js
install:
  - npm install codecov -g
node_js:
  - "9.8"
cache:
  directories:
    - node_modules
notifications:
  email: false
sudo: required
dist: trusty
group: edge
before_install:
  - export CHROME_BIN=/usr/bin/google-chrome
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - sudo apt-get update
  - sudo apt-get install -y libappindicator1 fonts-liberation
  - wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
  - sudo dpkg -i google-chrome*.deb
  - npm install -g firebase-tools
  - npm install -g @angular/cli
  - npm install -g opencollective
  - npm install -g commitizen
  - npm install -g cz-conventional-changelog
before_script:
  - npm prune
  - export CHROME_BIN=/usr/bin/google-chrome
  - export DISPLAY=:99.0
  - chmod +x ./ci/*.sh
script:
  - ./ci/setup.sh
  - ./ci/test.sh
after_success:
  - codecov
  - npm run report-coverage
  - 'if [ "${TRAVIS_PULL_REQUEST}" = "false" ]; then ./ci/deploy.sh; fi'
branches:
  only:
    - master
