language: node_js
node_js:
  - "9.8"
cache:
  directories:
    - node_modules
notifications:
  email: false
sudo: required
dist: trusty
group: edge
cache:
  directories:
  - $HOME/.yarn-cache
before_install:
  - sh -e /etc/init.d/xvfb start
  - sudo apt-get update
  - sudo apt-get install -y libappindicator1 fonts-liberation
  - sudo apt-key adv --keyserver pgp.mit.edu --recv D101F7899D41F3C3
  - echo "deb http://dl.yarnpkg.com/debian/ stable main" | sudo tee /etc/apt/sources.list.d/yarn.list
  - sudo apt-get update -qq
  - sudo apt-get install -y -qq yarn
  - wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
  - sudo dpkg -i google-chrome*.deb
install:
  - wget https://yarnpkg.com/latest.tar.gz && tar -xf latest.tar.gz && dist/bin/yarn
  - yarn global add codecov -g
  - yarn global add firebase-tools
  - yarn global add @angular/cli
  - yarn global add opencollective
  - yarn global add commitizen
  - yarn global add cz-conventional-changelog
install:
  - yarn
before_script:
  - export CHROME_BIN=/usr/bin/google-chrome
  - export DISPLAY=:99.0
  - chmod +x ./ci/*.sh
script:
  - ./ci/setup.sh
  - ./ci/test.sh
after_success:
  - codecov
  - yarn report-coverage
  - 'if [ "${TRAVIS_PULL_REQUEST}" = "false" ]; then ./ci/deploy.sh; fi'
branches:
  only:
    - master
